services:
  grass:
    container_name: grass
    restart: unless-stopped
    image: alone/grass
    ports:
      - "${HOST_PORT-8082}:8080/tcp"
    volumes:
      - ~/.local/share:/root/.local/share
    environment:
      - VNC_PASS=${VNC_PASS-CHANGE_IT}
    mem_limit: 1g
    privileged: true
