services:
  grass:
    container_name: grass
    restart: unless-stopped
    image: ccr.ccs.tencentyun.com/alone/grass
    ports:
      - "${HOST_PORT-8082}:8080/tcp"
    volumes:
      - ~/.local/share:/root/.local/share
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VNC_PASS=${VNC_PASS-CHANGE_IT}
    # cpus: 1
    # mem_limit: 1g
    privileged: true
