name: Build and Push Docker Image
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Determine branch
        id: vars
        run: |
          branch=$(echo ${GITHUB_REF#refs/heads/})
          echo "::set-output name=branch::$branch"
          if [ "$brancs" = "main" ]; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::$branch"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.branch }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/grass:${{ steps.vars.outputs.tag }}
