name: Build and Push Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: false
        default: ''
  schedule:
    - cron: "0 20 */2 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker tags
        run: |
          ver="${{ github.event.inputs.version }}"
          if [ -n "$ver" ]; then
            tags="type=raw,value=$ver"
          else
            ver=$(curl -s https://files.getgrass.io/file/grass-extension-upgrades/desktop-installer-latest.json | jq -r '.version')
            ver=${ver/v/}
            tags=$({
              echo "type=raw,value=$ver"
              echo "type=raw,value=latest"
            })
          fi
          echo "VERSION=$ver" >> $GITHUB_ENV
          {
            echo 'ALL_TAGS<<EOF'
            echo "$tags"
            echo "type=raw,value=${ver%.*}"
            echo "type=raw,value=${ver%.*.*}"
            echo EOF
          } >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/grass
            ghcr.io/${{ github.repository_owner }}/grass
            ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/grass
          tags: ${{ env.ALL_TAGS }}

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to QCloud CR
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.QCLOUD_CR_USER }}
          password: ${{ secrets.QCLOUD_CR_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            APP_VERSION=${{ env.VERSION }}
          platforms: linux/amd64 #,linux/arm64
